"""SQLAlchemy declarative base.

Every model in `app/models/` inherits from `Base`, which collects their
table definitions into `Base.metadata` — the single source of truth Alembic
compares against the live database when autogenerating migrations.
"""

from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase

# TEACHING NOTE — constraint naming conventions:
# Without this, PostgreSQL invents names for constraints/indexes
# (e.g. "users_email_key"), and those names differ across databases.
# Alembic then cannot reliably DROP a constraint it cannot name.
# Declaring a convention up front gives every constraint a deterministic
# name and makes autogenerated migrations reproducible.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(referred_table_name)s_%(column_0_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Base class for all ORM models (SQLAlchemy 2.0 style)."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)
