"""initial users and items tables

Revision ID: 0001
Revises:
Create Date: 2026-07-10

TEACHING NOTE — anatomy of a migration:
`upgrade()` moves the schema forward one step; `downgrade()` undoes exactly
that step. Together the chain of revisions can rebuild (or unwind) the
schema of any environment. Rules of thumb:
- NEVER edit a migration that has been applied anywhere but your machine —
  add a new one instead (others' databases already ran the old file).
- Always eyeball autogenerated migrations before committing: autogenerate
  is a diff tool, not a mind reader (it can't detect column *renames* —
  it sees a drop + an add, which would destroy data).
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # op.f() marks a name as already following our naming convention
    # (see app/db/base.py) so Alembic won't try to re-derive it.
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    # unique=True + index=True on the model becomes a single UNIQUE INDEX —
    # it enforces uniqueness AND accelerates lookup-by-email.
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)

    op.create_table(
        "items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        # Tables must be created in dependency order: items references
        # users, so users had to exist first (and be dropped last, below).
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_items_users_owner_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_items")),
    )
    op.create_index(op.f("ix_items_owner_id"), "items", ["owner_id"], unique=False)
    op.create_index(op.f("ix_items_title"), "items", ["title"], unique=False)


def downgrade() -> None:
    # Mirror image of upgrade(), in reverse order.
    op.drop_index(op.f("ix_items_title"), table_name="items")
    op.drop_index(op.f("ix_items_owner_id"), table_name="items")
    op.drop_table("items")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
