"""users: email as primary key, optional username, split full_name

Revision ID: e7a31f5c9d02
Revises: c4f8a2d91b37
Create Date: 2026-07-14

TEACHING NOTE — this migration was written BY HAND, not autogenerated:
autogenerate sees a primary-key swap as unrelated drops/adds and a column
split (full_name → first_name + last_name) as a drop + two adds, which
would destroy data. Three lessons on display:
1. Order matters: the FK from items to users must be dropped before the
   users PK it points at, and re-created only after the new PK exists.
2. Data moves inside the migration (UPDATE ... FROM) so schema and data
   change in the same transaction — postgres DDL is transactional, so a
   failure rolls back BOTH.
3. The name split is best-effort ("first word / rest"); a reversible
   perfect split doesn't exist, which is exactly why renames/splits
   deserve hand-written migrations and a review.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e7a31f5c9d02"
down_revision: Union[str, None] = "c4f8a2d91b37"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- users: new columns -------------------------------------------------
    op.add_column("users", sa.Column("username", sa.String(length=50), nullable=True))
    op.add_column(
        "users", sa.Column("first_name", sa.String(length=255), nullable=True)
    )
    op.add_column("users", sa.Column("last_name", sa.String(length=255), nullable=True))
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)

    # Split "First Rest Of Name" on the FIRST space; a single-word name
    # becomes first_name only.
    op.execute(
        """
        UPDATE users SET
            first_name = CASE
                WHEN full_name LIKE '% %' THEN split_part(full_name, ' ', 1)
                ELSE full_name
            END,
            last_name = CASE
                WHEN full_name LIKE '% %'
                    THEN substring(full_name FROM position(' ' IN full_name) + 1)
                ELSE NULL
            END
        WHERE full_name IS NOT NULL
        """
    )
    op.drop_column("users", "full_name")

    # --- items: re-key the owner FK from users.id to users.email ------------
    op.add_column(
        "items", sa.Column("owner_email", sa.String(length=255), nullable=True)
    )
    op.execute(
        "UPDATE items SET owner_email = u.email FROM users u WHERE items.owner_id = u.id"
    )
    op.alter_column("items", "owner_email", nullable=False)
    op.drop_constraint(op.f("fk_items_users_owner_id"), "items", type_="foreignkey")
    op.drop_index(op.f("ix_items_owner_id"), table_name="items")
    op.drop_column("items", "owner_id")

    # --- users: swap the primary key ----------------------------------------
    # Safe to drop now: nothing references users.id anymore.
    op.drop_constraint(op.f("pk_users"), "users", type_="primary")
    op.drop_column("users", "id")
    # The PK brings its own unique index; the old standalone one is
    # redundant the moment email becomes the key.
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_primary_key(op.f("pk_users"), "users", ["email"])

    # --- items: FK to the new PK ---------------------------------------------
    # onupdate="CASCADE" because the email PK is a NATURAL key that can
    # change (a user edits their email): postgres then rewrites
    # items.owner_email rows itself, atomically.
    op.create_foreign_key(
        op.f("fk_items_users_owner_email"),
        "items",
        "users",
        ["owner_email"],
        ["email"],
        ondelete="CASCADE",
        onupdate="CASCADE",
    )
    op.create_index(op.f("ix_items_owner_email"), "items", ["owner_email"])


def downgrade() -> None:
    # Mirror image, in reverse dependency order. The regenerated ids are
    # NEW values — surrogate keys carry no meaning, so that is acceptable;
    # the full_name concatenation is likewise best-effort.
    op.drop_index(op.f("ix_items_owner_email"), table_name="items")
    op.drop_constraint(op.f("fk_items_users_owner_email"), "items", type_="foreignkey")

    op.drop_constraint(op.f("pk_users"), "users", type_="primary")
    op.execute("ALTER TABLE users ADD COLUMN id SERIAL")
    op.create_primary_key(op.f("pk_users"), "users", ["id"])
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)

    op.add_column("items", sa.Column("owner_id", sa.Integer(), nullable=True))
    op.execute(
        "UPDATE items SET owner_id = u.id FROM users u WHERE items.owner_email = u.email"
    )
    op.alter_column("items", "owner_id", nullable=False)
    op.create_foreign_key(
        op.f("fk_items_users_owner_id"),
        "items",
        "users",
        ["owner_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(op.f("ix_items_owner_id"), "items", ["owner_id"])
    op.drop_column("items", "owner_email")

    op.add_column("users", sa.Column("full_name", sa.String(length=255), nullable=True))
    op.execute(
        """
        UPDATE users SET full_name = NULLIF(
            TRIM(CONCAT(COALESCE(first_name, ''), ' ', COALESCE(last_name, ''))), ''
        )
        """
    )
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_column("users", "username")
    op.drop_column("users", "first_name")
    op.drop_column("users", "last_name")
