"""add listings

Revision ID: abd5ed073b85
Revises: 0001
Create Date: 2026-07-10 16:53:45.760327

TEACHING NOTE — this file was produced by `alembic revision --autogenerate`
(`make makemigration m="add listings"`): Alembic diffed Base.metadata (which
gained the Listing model) against the live schema and wrote the DDL below.
It was then reviewed by a human — always do that — and only this comment was
added. Note `Revises: 0001`: revisions form a linked list, which is how
`alembic upgrade head` knows the order to apply them in.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "abd5ed073b85"
down_revision: Union[str, None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "listings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("city", sa.String(length=120), nullable=False),
        sa.Column("country", sa.String(length=120), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_listings")),
    )
    op.create_index(op.f("ix_listings_city"), "listings", ["city"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_listings_city"), table_name="listings")
    op.drop_table("listings")
    # ### end Alembic commands ###
